### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by mguinness** [cmader/HttpClient-WearOS#1]
Thanks for producing this Wear OS app.  Definitely fits a niche for wearable devices.  

I did encounter an issue when trying to change the base url.  When I pressed to change, the screen went blank with nothing displayed instead of an on-screen keyboard.  The fix was found in [Gboard is broken in some Wear OS apps](https://www.androidpolice.com/gboard-broken-on-wear-os/).

I also have a few suggestions that you can consider below:

* When editing base url, the existing entry should be shown on the keyboard rather than being blank
* When a button is pressed it should indicate a request in progress (maybe by changing button color)
* ~~If there is no internet connectivity then buttons should be disabled to prevent showing an exception~~

It would also be nice to have an api key setting in configuration that would include a http header X-API-KEY with all requests.   That would give the ability for the web server or reverse proxy to reject the request if the correct value wasn't supplied.

**Comment by cmader** [comment]
Hi!

Thanks a lot for your comments, very much appreciated! I will have a look at the process for entering the base url. That part of the app is still a bit experimental and definitely needs improvement. Your other suggestions are great as well, I'll try to implement them in the future versions.

**Comment by cmader** [comment]
I just uploaded v1.0.2 to the repo with improvements regarding user feedback and entering the endpoint url. Button presses now cause a short vibration of the device and as long as a request is in process, the endpoint button is displayed a little bit darker. I also changed the way the endpoint base URL is entered. Still not perfect, but hopefully works around that gboard bug and it always displays the currently entered URL.
The X-API-KEY feature is certainly valid as well but I did not tackle that now. I'm wondering how long such api keys can become and if it really makes sense to enter them directly on the watch. Maybe a better place would be an endpoints definition file or some special config file.

**Comment by mguinness** [comment]
That's great!  Tested and can confirm that Gboard is working and previous URL is shown.  Button press feedback works and I like the vibration.

WRT to the API key it can be any length.  It's just a secret to protect *all* endpoints (including /endpoints) when exposed to the internet via reverse proxy.

**Comment by cmader** [comment]
I added the option for sending an API key. Keep in mind that the /endpoints response needs to have the "Content-Type" header set to "text/plain" now, which was previously not required.

**Comment by mguinness** [comment]
Thanks, tested and working.  For others using nginx just add the following to your site config:

```
if ($http_x_api_key !~ "my-api-key") {
  return 401;
}
```
